### ISSUE TITLE
Customize the login parameters

### ISSUE THREAD

**Issue by zhangysh1995** [chaos-mesh/wreck-it#11]
Hi,

Trying to run pivot, however, it throws:

> root@chcpu12i:/home/zhangys/utility/wreck-it# bin/pivot -d "root@tcp(127.0.0.1:3306)/sbtest"
> panic: new pivot failed, error: Error 1698: Access denied for user 'root'@'localhost'
> /home/zhangys/utility/wreck-it/pkg/connection/connection.go:62:
> /home/zhangys/utility/wreck-it/pkg/connection/connection.go:54:
> /home/zhangys/utility/wreck-it/pkg/executor/executor.go:46:
> 
> 
> goroutine 1 [running]:
> main.main()
>         /home/zhangys/utility/wreck-it/cmd/pivot/main.go:27 +0x2fa

Anyway I could pass parameters to the program? I'm new to Go so don't know how to change the source code. Could you kindly point out the code location to change it?

**Comment by zhouqiang-cl** [comment]
@zhangysh1995 Do you want pass password to it?

**Comment by zhouqiang-cl** [comment]
@zhangysh1995 here https://github.com/chaos-mesh/wreck-it/blob/master/cmd/pivot/main.go#L19

**Comment by mahjonp** [comment]
It can only work on TiDB on current phase. @zhangysh1995

**Comment by zhangysh1995** [comment]
> It can only work on TiDB on current phase. @zhangysh1995

So currently I cannot run it against MySQL?

**Comment by zhouqiang-cl** [comment]
> > It can only work on TiDB on current phase. @zhangysh1995
> 
> So currently I cannot run it against MySQL?

Yes. The AST tree  base on http://github.com/pingcap/parser

**Comment by zhouqiang-cl** [comment]
And if you need set password, you can use the dsn  like this `user:passwd@tcp(%s:%d)/test`
